# Extended Tasks

## Task 1

In [32]:
import requests
import feedparser
from bs4 import BeautifulSoup
import json
import pandas as pd

In [45]:
def getArticleDetailsByUrl(url):
    page = requests.get(url)
    soup = BeautifulSoup(page.text,"html.parser")
    
    headline = soup.title.string
    subheadline = soup.head.find("meta",attrs={"name":"description"}).get('content')

    doc_body = ''
    if "The Irish Times" in soup.text:
        for body_p_tag in soup.article.find_all("p", attrs={"class": "no_name"}):
            doc_body += body_p_tag.get_text() + " "

    source = "Other"
    try:
        if "irishtimes" in url:
            source = "IrishTimes"
            body_p_tag = soup.article.find("div", attrs={"class": "last_updated"}).find("p")
    except:
        pass

    first_sentence = doc_body.split(".")[0]
    return [headline, subheadline, first_sentence, doc_body, source]

RSSfeed = feedparser.parse('http://www.irishtimes.com/cmlink/news-1.1319192')
i = 1
FeedDataframe = pd.DataFrame({'Article_ID': [], 'Title': [], 'Content': []})   
for item in RSSfeed['entries']:
    article_url = item['link']
    [headline, subheadline, first_sentence, doc_body, source] = getArticleDetailsByUrl(article_url) 
    FeedDataframe = FeedDataframe.append({'Article_ID':int(i), 'Title':headline, 'Content':doc_body},ignore_index=True)
    i+=1
    
FeedDataframe['Article_ID'] = FeedDataframe.Article_ID.astype(int)
FeedDataframe.set_index('Article_ID', inplace=True)
FeedDataframe.head(5)

,Content,Title
Article_ID,,
1,The top prizes in this yearâ€™s European Union C...,EU Contest for Young Scientists features starc...
2,A few years ago entrepreneur and multimilliona...,Junior entrepreneurs encouraged to start real ...
3,A report has called for new guidelines for jud...,New personal injury measures needed to reduce ...
4,A major programme of compulsory purchasing of...,Councils should buy vacant houses compulsorily...
5,When Alvaro Cabello came to Ireland in 2012 it...,Unemployment main driver for Spaniards moving ...

## Task 2

In [54]:
from twitter import Twitter, OAuth, TwitterHTTPError, TwitterStream

ACCESS_TOKEN = '2839893905-pBXUzdrHCNXyjfPuBpSwxNbH1zyEpRaa2sXK0Jd'
ACCESS_SECRET = 'eNtB7YTAfsMhPIQtKji8aQT7zQFpFfDPR2lQ89WKfgI1U'
CONSUMER_KEY = 'ZqPrfLpc0znZlz3kW2a22VmUa'
CONSUMER_SECRET = 'BHD19T0DmUV2XVvEhUAgvpXMx0nGfxevAtr53NbCd9jQjPyTqn'

oauth = OAuth(ACCESS_TOKEN, ACCESS_SECRET, CONSUMER_KEY, CONSUMER_SECRET)
twitter = Twitter(auth=oauth)
iterator = twitter.search.tweets(q='#analytics', result_type='recent', lang='en', count=100)

file = open("twitter_search_100tweets.json", "w") 

for a in iterator['statuses']:
    file.write(json.dumps(tweet)+"\n")
file.close()

with open("twitter_search_100tweets.json") as file:
    tweetsCombined = map(json.loads, file.readlines())
    tweets = []
    
    for tweet in tweetsCombined:
        user_id = tweet['user']['id']
        text = tweet['text'] 
        retweets = tweet['retweet_count'] 
        retweet = tweet['in_reply_to_user_id'] 
        tweet_data_list.append((user_id, text, retweet_count, user_retweet))

In [55]:
columns=['User ID', 'Text', 'No. Retweets', 'User Retweet']
df = pd.DataFrame(tweet_data_list, columns=columns) 
df.head(5)

,User ID,Text,No. Retweets,User Retweet
0,919744697551253505,RT @patentpia_kgt: Bosch has been actively dev...,3,NaN
1,3100230334,Tomorrow's Energy and the Power of Real-Time #...,0,NaN
2,3085247581,ðŸ”ŒWhat are the 7 Key #Marketing Concepts In The...,0,NaN
3,4496967314,RT @KineticaHQ: Our GPU-accelerated database f...,1,NaN
4,793721694741561344,You deserve better and you know it =&gt; Direc...,0,NaN